### ISSUE TITLE
Add hovertext / mouseover / tooltip for datapoints on the SVG

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#127]
Start with the simplest possible thing, like the datapoint value, and go from there!

PS: Note that this is already done in the interactive (codename: dynagraphs) version of the graphs.

**Comment by adamwolf** [comment]
There are a few different ways to implement this, and I'm pretty scared of
what some of them would do to my duodeutsch graph that's already 4.5 megs.

**Comment by saranli** [comment]
I am not sure whether this would be worth doing before moving to client-side graphs. This would require potentially downloading all the datapoints, and perhaps generating an intermediate file of some sort correlating them with their coordinates on the svg. Since the interactive graphs already have tooltips, would it not be better to just focus on client-side graphs?
