### ISSUE TITLE
Leaking isolines

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#141]
## Reseminata

1. Generate graph for one of the following bb files in the test suite:

* leaky-missing-ybhp-lines1.bb
* leaky-missing-ybhp-lines2.bb (pictured below)
* leaky-missing-ybhp-lines3.b
* leaky-ybhp-lines-wl1.bb
* leaky-ybhp-lines-wl2.bb
* leaky-ybhp-lines-wl3.bb

## Expectata

Yellow isolines should always be on the good side of the razor road.

## Resultata

Notice the leakage.

![image](https://user-images.githubusercontent.com/9928/88576345-2489b680-cffa-11ea-89f0-89d2f093010c.png)

**Comment by saranli** [comment]
I think my latest commit seems to have resolved at least the leaky lines part. I am not sure about the missing lines part, since that is probably related to the decision of how many guidelines to draw and/or whether the good side of the road will be shaded or not. More info on the "missing" part is needed.

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3480
