### ISSUE TITLE
Non-monotone isolines on a do-less graph

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#205]
I believe this nonmonotonicity is a bug:

![image](https://user-images.githubusercontent.com/9928/116940057-31d76f80-ac22-11eb-9491-843519e81e8a.png)

Consider the thin green line denoting 7 days of safety buffer and where it jumps down. That's like a week before the red line jumps up. But the red line jumping up means the do-less goal gets easier. It doesn't make sense for you to need to suddenly do even less of what you're do-lessing in order to maintain your 7 days of safety buffer.

## Replicata

1. Run https://github.com/beeminder/privatesuite/blob/master/data/isolines-nonmon.bb through Beebrain

## Expectata

Strictly monotone isolines.

## Resultata

The nonmonotonicity we see in the screenshot above.

## Cognata

* #239 

_**Verbata**: isolines, PPR function, graph aesthetics,_

**Comment by saranli** [comment]
The issue here is what to do with the PPR when there is a vertical segment. As of now, when beebrain encounters an infinite segment, I think it use PPR=0 for that day. On the other hand, a nearly vertical segment uses 2*r for that segment. For the editor, that results in "discontinuous" behavior, wherein if one edits a knot for a segment to make it vertical, the PPR for the starting day for that segment remains at 2*r during the editing process, except when the segment is vertical, when it becomes 0. This causes the guidelines to show inconsistent behavior for nearly vertical vs vertical segments.

Now, I had implemented the ppr() function in beebrain to use ppr=2*(vfinal-vstart) for the vertical segment since that made the guideline behavior smooth and hence is (what I think) makes consistent sense, but this now conflicts with beebrain (more like, beebody when it adds the PPR point for that day). It is an easy fix if the inconsistent behavior is the accepted one.

**Comment by saranli** [comment]
Here is what guidelines look like for near-vertical segments:
![image](https://user-images.githubusercontent.com/1292086/141342201-0b90be57-1cba-4a3d-bd17-16bfcdd10222.png)
Here it is for vertical lines with the current code:
![image](https://user-images.githubusercontent.com/1292086/141342407-58cf7c3f-02c0-4716-a51e-4939fcfbc32b.png)
Here is what it looks like with vertical lines if I fix it by making it ppr=0 for vertical segments:
![image](https://user-images.githubusercontent.com/1292086/141343339-f31611d9-fa6e-41f6-b671-7ddf16228f21.png)

**Comment by saranli** [comment]
I have implemented an update on the isoline generation for doless goals that now matches what the beebody does for ppr's when vertical jumps are present. Here is what graphs looked like before:
![image](https://user-images.githubusercontent.com/1292086/166145675-3b95f643-4f64-4195-b55b-36a7bc4dd6c3.png)
and here is what they look like after the update:
![image](https://user-images.githubusercontent.com/1292086/166145698-8cbc5a5d-f880-4dc6-9734-32edfad55c61.png)
As far as I can tell, the updated isolines should be correct with respect to the actual beebody ppr function, which simply passes over vertical jumps without change.

**Comment by saranli** [comment]
Here is another before:
![image](https://user-images.githubusercontent.com/1292086/166146024-bb86bacc-0408-486f-83a6-131a454633f1.png)
and after:
![image](https://user-images.githubusercontent.com/1292086/166146038-25b3020c-eca6-4663-8fd8-0bb754b69ce5.png)

**Comment by dreeves** [comment]
http://beeminder.com/changelog#4131
