### ISSUE TITLE
Ancient tluz with no "recommit" datapoint

### ISSUE THREAD

**Issue by bsoule** [beeminder/road#223]
Background: https://github.com/beeminder/beeminder/issues/1143 (see also https://github.com/beeminder/beeminder/issues/1302 may be related).

Some people *really* want to delete that "RECOMMITTED" datapoint, and sometimes it is fine, but sometimes it derails them. I just uploaded an example bb file to privatesuite that is the latter case. It's a goal that was recommitted on yesterday, and deleting the "recommitted" datapoint derails it.

If you run the file through beebrain, and look at the .json output (which gets stored as bb in beebody), it has `loser=true`, and `tluz=1625155200` -- which happens to be the day after the last datapoint entered prior to the derail. 

I think this is related to the stuff we do where we try to be smart about the asof(?) for goals that are derailed. If something derailed on 2016-04-29 and is still derailed today, we don't want to show a flatline to today, 2021-07-20. We want the goal to show as derailed years ago. So in this goal's case, without the RECOMMITTED datapoint, beebrain doesn't know to flatline the datapoint all the way to today, and instead reports the goal as having been lost ages ago. Beebody sees that `tluz` value, and goes "oh! the goal must be derailed" and recommits it. 

BB file: cant-delete-recommit.bb

**Comment by bsoule** [comment]
Looking at the beebody code, we do send in an explicit `asof` parameter in the bb file, and maybe that's the problem? Maybe beebrain is trying to be too clever because we're being rather indiscriminant with that asof. 

`params[:asof] = params[:asof] ? params[:asof] : now.to_s(:ds)`

In otherwords, we're basically** always saying that the `asof` is NOW , and leaving it to beebrain to decide on what actual asof makes sense. One possible fix for this would be to make beebrain less clever and punt the work over to beebody, and depend on beebody to send in an actual thoughtful asof.

** except in whatever rare cases we pass an explicit asof along -- rare because it's not a setting that's available in the interface, so it's almost never used, and the behavior when it is something other than "now" is kind of ill-defined and in my experience, stuff usually breaks when you try to use it.

**Comment by dreeves** [comment]
Clarification: Beebody is always sending an actual daystamp (eg, "20210903") for the `asof` parameter and Beebrain would error out if it didn't. (You may have said that but also contradicted it in your footnote?)

In any case, I believe you're on the wrong track with `asof` in particular but correct about Beebrain overcleverness. Beebrain flatlines up to the last datapoint, not today. (Exception: do-less/rash which always flatline to today.) That often is nicer because maybe you derailed years ago and by flatlining to the last datapoint you can actually see that ancient derailment on the graph. If we flatlined to today, the graph would look stupid and boring, with everything interesting squished to the left and then a years-long flatline with a little triangle at the end.

But if the graph is finally being rerailed then we *must* flatline up to today. Failure to do that is the bug.

I'm on it!

**Comment by dreeves** [comment]
The fix is pushed! It solved #222 along the way and improved the following as well:

Before/After on not flatlining far enough:

![image](https://user-images.githubusercontent.com/9928/132164523-9f743c56-6d3e-4e4c-8beb-412f938156e3.png)

Another example:

![image](https://user-images.githubusercontent.com/9928/132164581-fb7c3d94-8ca3-4462-8fec-de221dd96922.png)

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3873
http://beeminder.com/changelog#3874
