### ISSUE TITLE
Excess precision on y-axis

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#241]
HT krugerk for creating this fascinating monstrosity:

![image](https://user-images.githubusercontent.com/9928/147975600-80ed808a-8fd5-4f24-b217-c59fc8903975.png)

For me on Chrome (the next day) it renders like this:

![image](https://user-images.githubusercontent.com/9928/147975672-0fc3a084-71f1-473e-833e-53ffa735b8f6.png)

But in my dev env it looks like this:

![image](https://user-images.githubusercontent.com/9928/147975708-37a02572-a8aa-4661-8ed8-20d7b327f603.png)

So that's a weird heisenbug with the red line going crazy.

But either way, it seems like the choices for vmin and vmax should be smarter, like not allowed to be within some epsilon of each other?

This is red-rect.bb in privatesuite.

**Comment by bsoule** [comment]
In Safari the svg just wouldn't load. 

In beebody/production I tweaked the road value so that it was 6119.3 instead of 6119.306 and then beebody chose 3 digits of precision, and the graph displays sort of normally, though it has these vertical yellow lines, which is weird. If you zoom out there's a vertical jump in the road just prior to the present flat spot, so maybe those lines are a holdover somehow from that segment?

![Screen Shot 2022-01-03 at 12 49 05](https://user-images.githubusercontent.com/46881/147978833-9250ce9b-f5ec-4f5b-a1ae-d702eade0f08.png)

**Comment by dreeves** [comment]
Another instance:

![image](https://user-images.githubusercontent.com/9928/153512014-e5727029-3193-48e8-b29b-e981b0d746e7.png)

That's red-box.bb in privatesuite.

**Comment by dreeves** [comment]
http://beeminder.com/changelog#4129
