### ISSUE TITLE
More than one consecutive vertical segment shows as a "dip" in guidelines and the 7-day buffer line.

### ISSUE THREAD

**Issue by saranli** [beeminder/road#47]
There is a minor difference with pybrain when there are two consecutive vertical segments in the road. jsbrain draws all of them for guidelines, showing a "dip", particularly visible in the 7-day guidelines:

![image](https://user-images.githubusercontent.com/1292086/51116514-69853800-181c-11e9-8891-7d21666745a8.png)

This is visible in the testbb suite ffukuchi+meditation. One would need to modify guidelines path generation to skip such segments which is a bit challenging. I think showing the dip is in fact more accurate since the road matrix does include that detail.

**Comment by dreeves** [comment]
Here's how this looks post-YBHP (also zoomed in a bit):

![image](https://user-images.githubusercontent.com/9928/88850623-82580300-d1a0-11ea-9bf0-41b294e1d29e.png)

Since that's exactly what the road matrix specifies with that weird dip, I'm calling this A-OK. The isolines are all fine now too! So probably this should've been called a regression with the switch from Python to Javascript but is now moot. Woo-hoo! Thank you, Uluc!
