### ISSUE TITLE
Less overwhelming colors; bring back guiding lines?

### ISSUE THREAD

**Issue by dreeves** [beeminder/road#97]
It's proving hard to tone down the colors enough so they don't look garish and like we're trying to cram too much information into the graphs. Here's the best I've come up with so far:

![image](https://user-images.githubusercontent.com/9928/71965071-cd360d00-31b3-11ea-816a-5c6ac2321819.png)

In the old world order we had the yellow guiding lines to make it nice and obvious what the good side of the road is. We now have a red side and a green side, which makes a lot of sense.

Could we combine those approaches and have color-coded guiding lines? Maybe that would make the coloring subtle enough and we could also clearly demarcate the regions that way.

Basically just plot the appropriately colored isoline of the DTD function for every integer, including faint red lines below the razor road. (As with the guiding lines, there are edge cases, like if the graph is zoomed out enough or when it changes steepness, the lines can be too dense, but we could use the same algorithm for that as for the current yellow guiding lines.)

I don't know how that will look, but Mary's eager to try ideas to reduce the clutter/overwhelm.

----

Original idea from Mary:

Does it help to have the colored regions shown in the past? Could we reduce the [currently excessive] visual stimuli by having it only show that coloring for the segment starting, say, yesterday and going forward? Or, maybe even only for yesterday to the akrasia horizon?

Mary also said this about why to not care about colors in the past but I don't understand this part yet:

> The past will change depending on the rate. So, even if I had a week of space on December 1st, for instance, if I up the rate significantly, that's going to change, and that historical stuff is going to be kind of meaningless. So it's a lot of visual stimuli for no real info about the past. 

I'm skeptical that it will look good to have the colored regions abruptly stop and have been thinking in terms of just toning them down so they're reasonably subtle but I don't have a great eye for such things.

**Comment by bsoule** [comment]
danny just shared the latest with me and I really like it! (e.g. 
![image](https://user-images.githubusercontent.com/46881/72375352-c7af5a00-36c0-11ea-95d2-24ff74346fa4.png))

I like the parallel lines.. they make it look slightly 3Dish and.. i dunno. i like it.

It's tempting to ask for the yellow lines to make a gradient from yellow to green (for safe!), so that they're green from the 7-day line and out... but it's probably not a good idea because then you have green vs red again and they are look so strong and garish becaue they're complements. (but if it were just a matter of minutes to try it out, i might like to see that just in case it were awesome instead of garish?).

One other thought: a thing I tried in illustrator that I liked was I had the pink zone a darker red, similar to what you've got now, and the rest of the below-the-road red zone was several shades lighter. (the gray line pattern you have now is very similar in value to the red background, and I don't think it would hurt to have that area pop out a little bit more).

also here's a possibly fiddly question/request: in illustrator and maybe with html+css borders you can specify where a stroke is drawn along an object's edge, so that it is either outside, inside, or centered on the edge. is that possible / easy with the svg? I'm thinking of the red line, which is currently drawn so that the actual pixel edge of the region is in the center of the line (imagine if you increased the stroke to 30 pixels or something, you'd have 15 pixels above the line and 15 below). Is it possible to adjust that red stroke so that it's below the line and a safe datapoint reads as above the line, rather than *on* it?  Again, this is a fiddly request, so definitely not an imperative or anything, just that in some vector graphic contexts i know it is a simple configuration setting, so maybe i thought it could be simple here too?

![Untitled-1____53___CMYK_Preview_](https://user-images.githubusercontent.com/46881/72376577-03e3ba00-36c3-11ea-95d6-6f5aa0534d73.png)

**Comment by bsoule** [comment]
thumbs up! i liked the adjustment on the stroke placement, and that we can fiddle around with the shading of the pink zone & red zone separately!

**Comment by zedmango** [comment]
I really prefer Daniel's first graph, with the pastel color diagonal stripes. That bottom graph, with the solid thick parallel lines so close together, looks too cluttered and confusing, especially if you put a bunch of data points in there.

**Comment by dreeves** [comment]
http://beeminder.com/changelog#3334
